version: '3'
services:
  jupyter:
    build: ./
    command: jupyter lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root
    volumes:
      - ./:/code
    ports:
      - "8888:8888"
    env_file:
      - ./.env
